/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 chess.gltf --transform
Author: FatWasHere (https://sketchfab.com/fathin880)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wooden-chess-classic-5f30282d57e4443588be447237669916
Title: Wooden Chess Classic
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('../chess-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube002_WoodPutih_0.geometry} material={materials.WoodPutih} />
      <mesh geometry={nodes.Cube018_WoodBlack_0.geometry} material={materials.WoodBlack} />
      <mesh geometry={nodes.Cube_Wood_0.geometry} material={materials.Wood} position={[0, 0.012, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.295, 0.295, 0.246]} />
      <mesh geometry={nodes.Cube001_WoodBlack_0.geometry} material={materials.WoodBlack} position={[0.014, 0.064, 0.002]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.246, 0.246, 0.286]} />
      <mesh geometry={nodes.Cube001_WoodPutih_0.geometry} material={materials.WoodPutih} position={[0.014, 0.064, 0.002]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.246, 0.246, 0.286]} />
      <mesh geometry={nodes.Cube001_Wood2_0.geometry} material={materials.Wood2} position={[0.014, 0.064, 0.002]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.246, 0.246, 0.286]} />
    </group>
  )
}

useGLTF.preload('../chess-transformed.glb')
