/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 mac.gltf --transform
Author: Michele (https://sketchfab.com/michelerispoli2009)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/imac-24-f8738ff85d4043598a9179ba6763bb4d
Title: iMac 24"
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/mac-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} position={[0.137, 1.832, 0.232]} rotation={[1.486, 0.036, -0.394]} scale={[0.2, 0.2, 0.2]} />
    </group>
  )
}

useGLTF.preload('/mac-transformed.glb')
