/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 piano.gltf --transform
Author: John Fino (tauricity) (https://sketchfab.com/tauricity)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hallet-and-davis-piano-1896-3dst19-5a0d2e4dea71474abb55b7c2bfb6e715
Title: Hallet And Davis Piano, 1896 #3DST19
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/piano-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Material_0} rotation={[-Math.PI, 0, 0]} scale={0.083} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.Material_1} rotation={[-Math.PI, 0, 0]} scale={0.083} />
      <mesh geometry={nodes.Object_4.geometry} material={materials.Material_2} rotation={[-Math.PI, 0, 0]} scale={0.083} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.Material_3} rotation={[-Math.PI, 0, 0]} scale={0.083} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Material_4} rotation={[-Math.PI, 0, 0]} scale={0.083} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.Material_5} rotation={[-Math.PI, 0, 0]} scale={0.083} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Material_6} rotation={[-Math.PI, 0, 0]} scale={0.083} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.Material_7} rotation={[-Math.PI, 0, 0]} scale={0.083} />
    </group>
  )
}

useGLTF.preload('/piano-transformed.glb')
